### ISSUE TITLE
Casts to groups (with more than one speaker) cannot be stopped, and will immediately reconnect

### ISSUE THREAD

**Issue by dday4thedeceiver** [SamDel/ChromeCast-Desktop-Audio-Streamer#53] opened 2019-07-26 17:51 UTC
To reproduce: create a group (with at least two devices - if the group has only one device, all is well). Cast from DAS, then click stop. DAS will immediately reconnect. 

This also happens if you start casting to a speaker in this group from elsewhere. The cast will start, however DAS will immediately reconnect, interrupting the other stream.

It may also be related that groups may show up twice in the device list, but this is not consistent. They are not duplicated in user.config

(As an obvious workaround I'm casting to individual devices, but the motivation to use groups is because they seemed to be more reliable in avoiding single device dropouts. I haven't been casting to multiple devices with 2.4 though, so that was based on experience with earlier versions)

**Comment by SamDel** [comment] 2019-07-27 08:22
> This also happens if you start casting to a speaker in this group from elsewhere. The cast will start, however DAS will immediately reconnect, interrupting the other stream.

I can confirm this one, it has to do with the [firmware upgrade](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/47). I think I can fix it later (group information has changed in the reply from the devices).

> To reproduce: create a group (with at least two devices - if the group has only one device, all is well). Cast from DAS, then click stop. DAS will immediately reconnect.

Stopping a group works as expected for me. Does it happen every time for you?

**Comment by dday4thedeceiver** [comment] 2019-07-28 14:23
Yes, it's pretty consistent, however I'm on 2.4 - will update to 2.4.5 and report back.

WRT to the alternative of casting to multiple devices,  the syncing gets pretty bad too.. however it's not a dealbreaker. There was a dropout but that's probably because the speaker was power-cycled..

**Comment by dday4thedeceiver** [comment] 2019-07-29 17:42
Stopping manually seems to be working fine with 2.4.5

**Comment by SamDel** [comment] 2019-10-01 03:50
Thamks. I think this is also fixed in 2.4.15. The device was restarting because of a bug in saving the known devices. See also [this](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/issues/52) issue.

Please reopen if it still occurs.

**Closed by SamDel** 2019-10-01 03:50 UTC
