### ISSUE TITLE
New version 3.6 reverts to old device list and reset settings exceptions Nullable Object

### ISSUE THREAD

**Issue by johnfoxii** [SamDel/ChromeCast-Desktop-Audio-Streamer#104] opened 2021-05-21 17:24 UTC
Installed 3.6 on top of 3.4 app would not start. Uninstalled and reinstalled. Startup show an old device list I had reset weeks ago.
When i went to reset (changed no other options) app exceptional

************** Exception Text **************
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at ChromeCast.Desktop.AudioStreamer.Application.ApplicationLogic.ResetSettings()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ChromeCast.Desktop.AudioStreamer
    Assembly Version: 3.6.0.0
    Win32 Version: 3.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Desktop%20Audio%20Streamer/Desktop%20Audio%20Streamer/ChromeCast.Desktop.AudioStreamer.exe
----------------------------------------

**Comment by johnfoxii** [comment] 2021-05-21 17:32
Clicked "continue" on exception. closed and restarted app. Was able to clear settings without exception.
solved?

**Comment by SamDel** [comment] 2021-05-21 19:05
The crash after resetting was caused by a bug: the new setting for converting multi channel audio to stereo wasn't properly initialized. I think it's solved for you because the new setting has a value now in the config after closing the application. The bug is fixed in version [3.7](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v3.7).

I don't know why the application failed to start after the upgrade. Is there an error in the Event Viewer - Windows logs - application?

Sorry about the bug, but thanks for letting me know!

**Closed** 2021-06-23 05:28 UTC
